name: meal_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ðŸ“Œ Added dependencies
  http: ^1.1.0
  url_launcher: ^6.2.4

  provider: ^6.0.5
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.0

  # ðŸ”¥ ADD THESE TWO LINES:
  firebase_auth: ^5.2.4
  cloud_firestore: ^5.4.4

  # ðŸ”” Local notifications for random recipe reminder
  flutter_local_notifications: ^17.2.0
  timezone: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # If you add images later, enable this:
  # assets:
  #   - assets/
